# Informações do Projeto
site_name: Hub do Torcedor - Documentação
site_author: Lucas
site_description: Documentação completa do projeto Hub do Torcedor, desenvolvido para a disciplina de TPPE.

# Configuração do Tema
theme:
  name: material
  language: pt
  palette:
    # Paleta para modo claro
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    # Paleta para modo escuro
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

# Navegação (Menus do Site) - VERSÃO CORRIGIDA E COMPLETA
nav:
  - 'Início': 'Documentacao/index.md'
  - '1. Concepção do Projeto':
      - 'Escopo do MVP': 'Documentacao/escopo.md'
      - 'Requisitos Elicitados': 'Documentacao/requisitos_elicitados.md'
      - 'Arquitetura': 'Documentacao/arquitetura.md'
      - 'Diagramas UML': 'Documentacao/diagramas_UML.md'
  - '2. Planejamento Ágil':
      - 'Backlog': 'Documentacao/backlog.md'
  - '3. Design e UI':
      - 'Guia de Estilo': 'Documentacao/style-guide.md'
      # Adicione prototipos.md e wireframes.md aqui quando os criar

# Extensões do Markdown
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - footnotes
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format